apiVersion: apps/v1
kind: Deployment
metadata:
  name: microser-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microser-java
  template:
    metadata:
      labels:
        app: microser-java
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: microser-java
        image: mpulgarf/microservicio-java-mpulgar:tagname:latest
        ports:
        - containerPort: 8080
          name: microser-java
        resources:
          requests:
            cpu: 2m
            memory: 400Mi
          limits:
            cpu: 1000m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: microser-java-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: microservicio-java-mpulgar
  type: LoadBalancer
