name: CI
on:
  
 push:
  branches: [ "feature-ms-miguelPulgar-mensaje" ]
 pull_request:
  branches: [ "feature-ms-miguelPulgar-mensaje" ]
  
 workflow_dispatch:
jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build
      run: |
       chmod +x gradlew
       ./gradlew build
       cd ./build
       ls -ltr

    - name: SonarCloud
      run: |
        chmod +x gradlew 
        ./gradlew build sonar -Dsonar.token=${{ secrets.SONARCLOUD_TOKEN }}
       
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.docker_user }}
        password: ${{ secrets.docker_password }}
    
    - name: Construccion docker
      run: |
       docker build . --file Dockerfile --tag mpulgarf/microservicio-java-mpulgar:latest
       docker push mpulgarf/microservicio-java-mpulgar
  deploy:
  
    runs-on: self-hosted
    needs: build  
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Minikube
        run: |
          echo "Iniciando despliegue en Kubernetes"
          kubectl apply -f deployments.yml
 
  performanceTests:
  
   runs-on: ubuntu-latest
   needs: deploy
   steps:

    - uses: actions/checkout@v3
    - name: Jmeter
      uses: QAInsights/PerfAction@v3.1
      with:
        test-plan-path: microservicio-java-mpulgar.jmx
        args: ''
          
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: result.jtl

  acceptanceTests:
 
   runs-on: self-hosted
   needs: deploy
   steps:
    - uses: actions/checkout@v3
    - name: Postman
      uses: matt-ball/newman-action@master
      with:
        collection: microservicio.postman_collection.json
    
